#!/usr/bin/env bash

# Append this to .bashrc
# For permanantely changing the terminal colors
termcolor = export PS1="\[\e[32m\][\[\e[m\]\[\e[31m\]\u\[\e[m\]\[\e[33m\]@\[\e[m\]\[\e[32m\]\h\[\e[m\]:\[\e[36m\]\w\[\e[m\]\[\e[32m\]]\[\e[m\]\[\e[33m\]\\$\[\e[m\] "
cat ${termcolor} >> ~/.bashrc

# To Add
    # Setup git configs
    # Setup SSH, print the key
    # Install Rust
        # curl https://sh.rustup.rs -sSf | sh
    # Check for updates on langs
    # detection for if WSL. If not,
        # install vs code, vlc, discord
        # install refind?